apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: wordpress
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::863518426750:role/cmtr-eso-irsa-role
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: wordpress
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql
  namespace: wordpress
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cmtr-ook9q7ho-secret